export default {
    LOGIN: "LOGIN",

    SIGNUP: "SIGNUP",

    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",

    ADD_TO_DO: "ADD_TO_DO",

    // GET_TOKEN : "GET_TOKEN",

    DELETE_TO_DO: "DELETE_TO_DO",

    REMOVE_TO_DO: "REMOVE_TO_DO",

    FETCH_TODO_SUCCESS: "FETCH_TODO_SUCCESS",

    UPDATE_TODO: "UPDATE_TODO",
}